### ISSUE TITLE
Error loading PickerPipeTools 0.1.1 with pipelayer 0.1.3 active

### ISSUE THREAD

**Issue by WonderDog** [Nexela/PickerPipeTools#1]
There is an error during load in PickerPipeTools 0.1.1 when pipelayer 0.1.3 is installed.

` Error ModManager.cpp:1024: Error in assignID, item with name 'pipelayer-bpproxy-pipe' does not exist. Source: pipelayer-bpproxy-pipe-clamped-E (pipe).`

**Comment by TheStaplergun** [comment]
Looking into getting this fixed. I'll have to speak with the mod owner to coordinate a fix.

**Comment by WonderDog** [comment]
I think it is how their mod substitutes different entities for each orientation to one crafting recipe.

**Comment by TheStaplergun** [comment]
It's due to the thing not having a same name item. I've already got a solution written, I'm just 90% through a new feature and can't roll back for a hotfix of a single incompatibility.

I'm working quickly to get this resolved. I haven't forgotten!

**Comment by TheStaplergun** [comment]
Resolved in 12b53518253c265954e7f3239cf40e99772d11e4
New version released containing fix.

**Comment by WonderDog** [comment]
Good News

**Comment by TheStaplergun** [comment]
So, there's a slew of other problems that have arisen related to fast replacement and other things going on. I've already notified the mod owner over at pipe layer.

**Comment by WonderDog** [comment]
Well I have not used pipe layer in this save as I only tried it out when I started and chose your tool to keep
