### ISSUE TITLE
clamped pipes in rotated or mirrored blueprints

### ISSUE THREAD

**Issue by 0ptera** [Nexela/PickerPipeTools#2]
When rotating or mirroring a blueprint with clamped pipes the result is a mess.

Original:
![2018-11-22-12-33-18-1706623](https://user-images.githubusercontent.com/8436934/48900531-ec0ffd80-ee52-11e8-93c3-29519f13de22.png)

Rotated 90°:
![2018-11-22-12-38-03-1866501](https://user-images.githubusercontent.com/8436934/48900738-8112f680-ee53-11e8-97dd-f78323a95680.png)

Rotated 180°:
![2018-11-22-12-33-29-5500361](https://user-images.githubusercontent.com/8436934/48900542-f500cf00-ee52-11e8-9cd2-f41fd292605b.png)

Mirrored:
![2018-11-22-12-33-36-1831528](https://user-images.githubusercontent.com/8436934/48900558-faf6b000-ee52-11e8-83f3-ceb01b55ccab.png)

As much as I'd love to get rid of flow control and use this instead without blueprint support it's almost useless to me.

**Comment by TheStaplergun** [comment]
I will have to see what sort of event is fired when the blueprint rotates and cause a rotation of the clamps. They're just pipes, and pipes don't rotate.

**Comment by TheStaplergun** [comment]
I have a solution. Gonna require a rework of the prototypes. Thanks for submitting the issue and please be patient! Might take me a bit, it's Thanksgiving weekend.

**Comment by 0ptera** [comment]
Take your time, I didn't expect a fix within the hour.

Would be nice if in the process you could shrink down pipe prototypes to straight, curve, T and X and rotate those instead of having one per rotation. Currently this adds a lot of prototypes to select in deconstruction planner.

**Comment by TheStaplergun** [comment]
That's actually, funny enough, gonna be one of the benefits of the rework. Glad I could solve two problems at once.

**Comment by Nexela** [comment]
This is also partly related to the way the mirroring works and will need
custom logic for it on that end.

**Comment by TheStaplergun** [comment]
It actually should correct itself with this change, because the type it's being changed to can be mirrored properly.

**Comment by TheStaplergun** [comment]
I've gotten the changes written. Im not sure if mirroring will work properly for elbow bend pipes. The mod owner for that might have to change it.
What I have written now will work though you'll have to go through and place your blueprints and reclamp all the pipes with the new ones, then blueprint that. They'll rotate properly now though.

Any pipes currently in the world from the old entity will be auto-replaced with the new version for you.

Do you have a copy of your save you can upload so I can test and ensure that the fix works in your map without problems?

**Comment by TheStaplergun** [comment]
Fixed in https://github.com/Nexela/PickerPipeTools/commit/57fbc91eeb34147ada1bc238f84c47cfb29feeef

Set up to properly support in blueprint mirroring in
https://github.com/Nexela/PickerExtended/commit/e98eef6b364a762b7a9a788ad4757dd7d29e1c76

**Comment by TheStaplergun** [comment]
Both mods have been updated in mod portal containing the above fixes and other features.
