### ISSUE TITLE
Error on load [1.0.1]

### ISSUE THREAD

**Issue by FabrizioMFE** [Nexela/PickerPipeTools#6]
Failed to load mods: Error in assignID, item with name 'factory-fluid-dummy-connector-4' does not exist.

Source: factory-dummy-connector-4-clamped-single (pipe-to-ground).

Mods to be disabled:
-PickerPipeTools

https://mods.factorio.com/mod/PickerPipeTools/discussion/5cea41ff2da14e000dc432d6

Still happening in version 1.0.1

**Comment by TheStaplergun** [comment]
This is explicitly related to Factorissimo. Will fix.
